#ifndef LIBLCC_CONFIG_H
#define LIBLCC_CONFIG_H

#cmakedefine LIBLCC_DEBUG

#define LIBLCC_ENABLE_STATIC_CONTEXT
#ifndef LIBLCC_EVENT_LIST_STATIC_SIZE
#define LIBLCC_EVENT_LIST_STATIC_SIZE 10
#endif

#define LIBLCC_MAJOR ${PROJECT_VERSION_MAJOR}
#define LIBLCC_MINOR ${PROJECT_VERSION_MINOR}
#define LIBLCC_MICRO ${PROJECT_VERSION_PATCH}

#endif
